# Generated by Django 3.2 on 2022-07-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbalance',
            old_name='balacnce',
            new_name='balance',
        ),
    ]
